version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: kratos-postgres
    restart: "no"
    working_dir: /application
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=core
      - POSTGRES_DB=core
      - POSTGRES_USER=core
    ports:
      - "5432:5432"
    networks:
      - intranet

  pgadmin:
    image: dpage/pgadmin4
    container_name: kratos-pgadmin
    restart: "no"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=core@example.com
      - PGADMIN_DEFAULT_PASSWORD=core
    ports:
      - "5433:80"
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos:v0.8.2-alpha.1
    container_name: kratos-migrate
    depends_on:
      - postgres
    environment:
      - DSN=postgres://core:core@postgres:5432/core?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    image: oryd/kratos:v0.8.2-alpha.1
    container_name: kratos
    depends_on:
      - kratos-migrate
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    restart: "no"
    environment:
      - DSN=postgres://core:core@postgres:5432/core?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    container_name: kratos-mailslurper
    restart: "no"
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:

volumes:
  postgres:
    name: vol-kratos
  pgadmin:
    name: vol-pgadmin
